version: 2

registries:
  npm-ghp-luminsports:
    type: npm-registry
    url: 'https://npm.pkg.github.com'
    token: ${{ secrets.GHP_ACCESS_TOKEN }}
  npm-fortawesome:
    type: npm-registry
    url: 'https://npm.pkg.github.com'
    token: ${{ secrets.FORTAWESOME_REGISTRY_TOKEN }}

updates:
  - package-ecosystem: npm
    directory: /
    registries: '*'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Australia/Adelaide
    groups:
      security-updates:
        applies-to: security-updates
