stages:
  - publishing

.configureNpm:
  before_script:
    - yarn --version
    - npm config set registry "https://verdaccio.luminsports.com/"
    - npm config set "//verdaccio.luminsports.com/:_authToken" "$VERDACCIO_PUBLISH_AUTH_TOKEN"

Publish:
  stage: publishing
  extends:
    - .configureNpm
  only:
    - tags
  image: node:latest
  script:
    - PACKAGE_VERSION=$(node -p "require('./package.json').version")
    - if [ "$PACKAGE_VERSION" != "$CI_COMMIT_TAG" ]; then echo "ERROR - tag does not match package.json version."; exit 1; fi
    - npm publish
