name: Create Release

on:
  push:
    branches:
      - '**'
    paths:
      - package.json

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Automatic GitHub Release
        uses: justincy/github-action-npm-release@2.0.2
        id: release

      - name: Setup Node
        uses: actions/setup-node@v3
        if: steps.release.outputs.released == 'true'
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@luminsports'

      - name: Publish
        if: steps.release.outputs.released == 'true'
        run: npm publish --registry https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
