name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Automatic GitHub Release
        uses: justincy/github-action-npm-release@2.0.2
        id: release

      - uses: actions/setup-node@v3
        if: steps.release.outputs.released == 'true'
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@luminsports'

      - name: Publish
        if: steps.release.outputs.released == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

